# Generated by Django 6.0 on 2026-02-11 15:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REVISION', 'Revisión')], max_length=20)),
                ('tipo_mantenimiento', models.CharField(blank=True, choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo')], max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, choices=[('PM1', 'PM1'), ('PM2', 'PM2'), ('PM3', 'PM3'), ('PM4', 'PM4'), ('LEVE', 'Leve'), ('MEDIANO', 'Mediano'), ('GRAVE', 'Grave')], max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('es_planificada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], max_length=10)),
                ('codigo_comprobante', models.CharField(max_length=50)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_insumo', models.CharField(choices=[('REPUESTO', 'Repuesto'), ('CONSUMIBLE', 'Consumible')], max_length=15)),
                ('stock', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('volvo', models.BooleanField(default=False)),
                ('ultimo_correlativo', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.dimension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Precio sin IGV', max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('INOPERATIVO', 'Inoperativo'), ('REPARADO', 'Reparado')], default='NUEVO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compra_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='app.compradetalle')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='app.actividadtrabajo')),
                ('item_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.itemunidad')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horometro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prioridad', models.CharField(choices=[('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia'), ('REGULAR', 'Regular')], max_length=15)),
                ('lugar', models.CharField(choices=[('TALLER', 'Taller'), ('CAMPO', 'Campo')], max_length=10)),
                ('ubicacion_detalle', models.CharField(blank=True, help_text='Ubicación exacta donde se realizará el trabajo', max_length=255)),
                ('estado_equipo', models.CharField(blank=True, choices=[('OPERATIVO', 'Operativo'), ('INOPERATIVO', 'Inoperativo')], max_length=15, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maquinaria')),
            ],
        ),
        migrations.AddField(
            model_name='actividadtrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app.ordentrabajo'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='app.proveedor'),
        ),
        migrations.CreateModel(
            name='TecnicoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordentrabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
            options={
                'unique_together': {('orden', 'tecnico')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.ManyToManyField(through='app.TecnicoAsignado', to='app.trabajador'),
        ),
        migrations.CreateModel(
            name='HistorialUbicacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('INOPERATIVO', 'Inoperativo'), ('REPARADO', 'Reparado')], default='NUEVO', max_length=15)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.almacen')),
                ('item_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='app.itemunidad')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.maquinaria')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ordentrabajo')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_registro', to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='TraspasoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrada', to='app.almacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salida', to='app.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('simbolo', models.CharField(blank=True, default='', max_length=10)),
                ('es_base', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='app.dimension')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumibles', to='app.actividadtrabajo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGrupoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.itemgrupo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='app.item')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_detalle', to='app.unidadmedida')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.unidadmedida'),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.unidadmedida'),
        ),
        migrations.CreateModel(
            name='UnidadRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=16)),
                ('activo', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='app.dimension')),
                ('unidad_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_base', to='app.unidadmedida')),
                ('unidad_relacionada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_relacionadas', to='app.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='app.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
            options={
                'unique_together': {('item', 'proveedor')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='compra',
            unique_together={('tipo_comprobante', 'codigo_comprobante')},
        ),
        migrations.CreateModel(
            name='UbicacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='app.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'nombre')},
            },
        ),
        migrations.AddConstraint(
            model_name='unidadmedida',
            constraint=models.UniqueConstraint(condition=models.Q(('es_base', True)), fields=('dimension',), name='unique_unidad_base_por_dimension'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together={('dimension', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='itemgrupodetalle',
            unique_together={('grupo', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='compradetalle',
            unique_together={('compra', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadrelacion',
            unique_together={('unidad_base', 'unidad_relacionada')},
        ),
    ]
