# Generated by Django 6.0 on 2026-01-22 03:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('REVISION', 'Revisión')], max_length=20)),
                ('tipo_mantenimiento', models.CharField(blank=True, choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo')], max_length=20, null=True)),
                ('subtipo', models.CharField(blank=True, choices=[('PM1', 'PM1'), ('PM2', 'PM2'), ('PM3', 'PM3'), ('PM4', 'PM4'), ('LEVE', 'Leve'), ('MEDIANO', 'Mediano'), ('GRAVE', 'Grave')], max_length=10, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_insumo', models.CharField(choices=[('REPUESTO', 'Repuesto'), ('CONSUMIBLE', 'Consumible')], max_length=15)),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=20)),
                ('volvo', models.BooleanField(default=False)),
                ('ultimo_correlativo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('gasto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('puesto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], max_length=10)),
                ('codigo_comprobante', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio sin IGV', max_digits=12, null=True)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('client_uid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='app.proveedor')),
            ],
            options={
                'unique_together': {('tipo_comprobante', 'codigo_comprobante')},
            },
        ),
        migrations.CreateModel(
            name='ItemUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('INOPERATIVO', 'Inoperativo'), ('REPARADO', 'Reparado')], default='NUEVO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='app.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='app.actividadtrabajo')),
                ('item_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.itemunidad')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(editable=False, max_length=50, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('horometro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prioridad', models.CharField(choices=[('URGENTE', 'Urgente'), ('EMERGENCIA', 'Emergencia'), ('REGULAR', 'Regular')], max_length=15)),
                ('lugar', models.CharField(choices=[('TALLER', 'Taller'), ('CAMPO', 'Campo')], max_length=10)),
                ('ubicacion_detalle', models.CharField(blank=True, help_text='Ubicación exacta donde se realizará el trabajo', max_length=255)),
                ('estado_equipo', models.CharField(blank=True, choices=[('OPERATIVO', 'Operativo'), ('INOPERATIVO', 'Inoperativo')], max_length=15, null=True)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maquinaria')),
            ],
        ),
        migrations.AddField(
            model_name='actividadtrabajo',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app.ordentrabajo'),
        ),
        migrations.CreateModel(
            name='TecnicoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ordentrabajo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabajador')),
            ],
            options={
                'unique_together': {('orden', 'tecnico')},
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tecnicos',
            field=models.ManyToManyField(through='app.TecnicoAsignado', to='app.trabajador'),
        ),
        migrations.CreateModel(
            name='HistorialUbicacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('INOPERATIVO', 'Inoperativo'), ('REPARADO', 'Reparado')], default='NUEVO', max_length=15)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.almacen')),
                ('item_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='app.itemunidad')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.maquinaria')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ordentrabajo')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_registro', to='app.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='TraspasoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrada', to='app.almacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salida', to='app.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='app.item')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.proveedor')),
            ],
            options={
                'unique_together': {('item', 'proveedor')},
            },
        ),
    ]
