# Generated by Django 6.0 on 2026-03-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
