# Generated by Django 6.0 on 2026-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unidadmedida',
            name='unique_unidad_base_por_dimension',
        ),
        migrations.AlterField(
            model_name='unidadrelacion',
            name='factor',
            field=models.DecimalField(decimal_places=12, max_digits=30),
        ),
    ]
