# Generated by Django 6.0 on 2026-01-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='client_uid',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='item',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='valor_unitario',
        ),
        migrations.RemoveField(
            model_name='itemunidad',
            name='compra',
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=3)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Precio sin IGV', max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
            ],
            options={
                'unique_together': {('compra', 'item')},
            },
        ),
        migrations.AddField(
            model_name='itemunidad',
            name='compra_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='app.compradetalle'),
        ),
    ]
