# Generated by Django 6.0 on 2026-02-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_unidadmedida_unique_unidad_base_por_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.DecimalField(decimal_places=6, max_digits=16)),
                ('cantidad_disponible', models.DecimalField(decimal_places=6, max_digits=16)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.almacen')),
                ('compra_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='app.compradetalle')),
                ('item', models.ForeignKey(limit_choices_to={'tipo_insumo': 'CONSUMIBLE'}, on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.almacen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.maquinaria')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ordentrabajo')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.trabajador')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.unidadmedida')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales', to='app.loteconsumible')),
            ],
        ),
    ]
