# Generated by Django 6.0 on 2026-04-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTrabajoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='actividades/evidencias/%Y/%m/')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='app.actividadtrabajo')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
