# Generated by Django 6.0 on 2026-02-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_unidadequivalencia_ubicacioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unidad_equivalencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.unidadequivalencia'),
        ),
        migrations.AddField(
            model_name='unidadequivalencia',
            name='categoria',
            field=models.CharField(choices=[('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud'), ('MASA', 'Masa'), ('AREA', 'Área'), ('TIEMPO', 'Tiempo'), ('OTRO', 'Otro')], default='OTRO', max_length=15),
        ),
        migrations.AddField(
            model_name='unidadequivalencia',
            name='simbolo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='unidadequivalencia',
            name='unidad_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unidadequivalencia',
            name='factor_a_unidad',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AddConstraint(
            model_name='unidadequivalencia',
            constraint=models.UniqueConstraint(condition=models.Q(('unidad_base', True)), fields=('categoria',), name='unique_unidad_base_por_categoria'),
        ),
    ]
