# Generated by Django 6.0 on 2026-05-04 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_actividadtrabajo_tipo_mantenimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado'), ('EN_PROCESO', 'En proceso'), ('RECIBIDO', 'Recibido')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('recepcion_confirmada', models.BooleanField(default=False)),
                ('fecha_confirmacion_recepcion', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.ordencompra')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_detalle', to='app.proveedor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('POR_REVISAR', 'Por revisar'), ('ENTREGADO', 'Entregado'), ('SIN_STOCK', 'Sin stock')], default='POR_REVISAR', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('recepcion_confirmada_tecnico', models.BooleanField(default=False)),
                ('fecha_confirmacion_tecnico', models.DateTimeField(blank=True, null=True)),
                ('confirmado_por_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_requerimiento_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_requerimiento_emitidas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_requerimiento_asignadas', to='app.trabajador')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_requerimiento', to='app.ordentrabajo')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrdenRequerimientoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item')),
                ('orden_requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.ordenrequerimiento')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_requerimiento_detalle', to='app.proveedor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
