# Generated by Django 6.0 on 2026-02-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_unidad_equivalencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('simbolo', models.CharField(blank=True, default='', max_length=10)),
                ('es_base', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=6, max_digits=16)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='unidadequivalencia',
            name='unique_unidad_base_por_categoria',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unidad_equivalencia',
        ),
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.dimension'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='app.dimension'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.unidadmedida'),
        ),
        migrations.AddField(
            model_name='unidadrelacion',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='app.dimension'),
        ),
        migrations.AddField(
            model_name='unidadrelacion',
            name='unidad_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_base', to='app.unidadmedida'),
        ),
        migrations.AddField(
            model_name='unidadrelacion',
            name='unidad_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relaciones_relacionadas', to='app.unidadmedida'),
        ),
        migrations.DeleteModel(
            name='UnidadEquivalencia',
        ),
        migrations.AddConstraint(
            model_name='unidadmedida',
            constraint=models.UniqueConstraint(condition=models.Q(('es_base', True)), fields=('dimension',), name='unique_unidad_base_por_dimension'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadmedida',
            unique_together={('dimension', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='unidadrelacion',
            unique_together={('unidad_base', 'unidad_relacionada')},
        ),
    ]
