# Generated by Django 6.0 on 2026-05-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_itemunidad_ubicacion_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='horometro_manual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maquinaria',
            name='horometro_manual_actualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
