# Generated by Django 6.0 on 2026-02-09 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_dimension_unidadmedida_unidadrelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.unidadmedida'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
    ]
