# Generated by Django 6.0 on 2026-02-09 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compradetalle_unidad_medida_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoconsumible',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.unidadmedida'),
        ),
    ]
