# Generated by Django 6.0 on 2026-05-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_historialubicacionitem_horometro_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialconsumible',
            name='horometro_fin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historialconsumible',
            name='horometro_inicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
