# Generated by Django 6.0 on 2026-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_movimientoconsumible_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoconsumible',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
