# Generated by Django 6.0 on 2026-02-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_movimientoconsumible_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemGrupoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.itemgrupo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='app.item')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_detalle', to='app.unidadmedida')),
            ],
            options={
                'unique_together': {('grupo', 'item')},
            },
        ),
    ]
