# Generated by Django 6.0 on 2026-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_compra_comprobante_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tipo_insumo',
            field=models.CharField(choices=[('REPUESTO', 'Repuesto'), ('CONSUMIBLE', 'Consumible'), ('HERRAMIENTA', 'Herramienta')], max_length=15),
        ),
    ]
