# Generated by Django 6.0 on 2026-05-20 15:14

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_orderequerimientodetalle_unidad_sin_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vb', models.BooleanField(default=False)),
                ('trabajos_a_realizar', models.TextField()),
                ('estado', models.CharField(choices=[('MAL', 'Mal'), ('REGULAR', 'Regular'), ('BUENO', 'Bueno')], default='REGULAR', max_length=10)),
                ('observacion', models.TextField(blank=True, default='')),
                ('sistema', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hora', models.TimeField()),
                ('apellidos', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('AUTORIZA', 'Autoriza'), ('VERIFICA', 'Verifica')], max_length=10)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='supervisores/firmas/%Y/%m/')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IPERC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=255)),
                ('descripcion_peligro', models.TextField()),
                ('consecuencia_peligro', models.TextField()),
                ('evaluacion_iperc', models.TextField()),
                ('evaluacion_riesgo_residual', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epp', models.TextField(blank=True, default='')),
                ('herramientas', models.TextField(blank=True, default='')),
                ('pregunta_1', models.BooleanField(default=False)),
                ('pregunta_2', models.BooleanField(default=False)),
                ('pregunta_3', models.BooleanField(default=False)),
                ('pregunta_4', models.BooleanField(default=False)),
                ('pregunta_5', models.BooleanField(default=False)),
                ('pregunta_6', models.BooleanField(default=False)),
                ('descripcion_tarea', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EncabezadoDocumentoEstandarizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=app.models.current_local_date)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_estandarizacion_creados', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_estandarizacion_revisados', to='app.trabajador')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumentoEstandarizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('recurso', models.CharField(max_length=255)),
                ('actividad', models.CharField(max_length=255)),
                ('detalle_actividad', models.TextField(blank=True, default='')),
                ('responsable', models.CharField(blank=True, default='', max_length=255)),
                ('nota_importante', models.TextField(blank=True, default='')),
                ('consideraciones', models.TextField(blank=True, default='')),
                ('encabezado_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.encabezadodocumentoestandarizacion')),
            ],
            options={
                'ordering': ['encabezado_documento_id', 'numero', 'id'],
                'unique_together': {('encabezado_documento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GestionCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('implementacion', models.TextField()),
                ('estado', models.CharField(choices=[('SUGERIDO', 'Sugerido'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('TERMINADO', 'Terminado')], default='SUGERIDO', max_length=15)),
                ('observacion', models.TextField(blank=True, default='')),
                ('iperc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones_cambio', to='app.iperc')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReporteIPERC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('iperc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='app.iperc')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_iperc', to='app.ordentrabajo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_iperc_supervisados', to='app.detallesupervisor')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_iperc', to='app.trabajador')),
            ],
            options={
                'ordering': ['orden_trabajo_id', 'secuencia', 'id'],
                'unique_together': {('orden_trabajo', 'trabajador', 'iperc', 'secuencia')},
            },
        ),
        migrations.CreateModel(
            name='MedidaCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detalle', models.TextField()),
                ('reporte_iperc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_correctivas', to='app.reporteiperc')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='detallesupervisor',
            name='reporte_iperc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_supervisor', to='app.reporteiperc'),
        ),
        migrations.AddField(
            model_name='detallesupervisor',
            name='reporte_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_supervisor', to='app.reporteorden'),
        ),
        migrations.CreateModel(
            name='SecuenciaControlRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actividad', models.TextField()),
                ('reporte_iperc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_control_riesgo', to='app.reporteiperc')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SoporteVisualDocumentoEstandarizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='estandarizacion/soportes/%Y/%m/')),
                ('detalle_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes_visuales', to='app.detalledocumentoestandarizado')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TareaPorEstandarizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre_tarea', models.CharField(max_length=255)),
                ('nivel_criticidad', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], default='MEDIO', max_length=10)),
                ('desarrollado', models.BooleanField(default=False)),
                ('area', models.CharField(max_length=100)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_por_estandarizar', to='app.item')),
            ],
            options={
                'ordering': ['codigo', 'id'],
            },
        ),
        migrations.AddField(
            model_name='encabezadodocumentoestandarizacion',
            name='tarea_por_estandarizar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_estandarizacion', to='app.tareaporestandarizar'),
        ),
    ]
