# Generated by Django 6.0 on 2026-05-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_checklisttaller_detallesupervisor_iperc_reporteorden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesupervisor',
            name='reporte_iperc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_supervisor', to='app.reporteiperc'),
        ),
        migrations.AlterField(
            model_name='detallesupervisor',
            name='reporte_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_supervisor', to='app.reporteorden'),
        ),
        migrations.AlterField(
            model_name='reporteiperc',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_iperc_supervisados', to='app.detallesupervisor'),
        ),
    ]
