# Generated by Django 6.0 on 2026-05-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_detallesupervisor_reporte_iperc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledocumentoestandarizado',
            name='posicion_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalledocumentoestandarizado',
            name='posicion_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='detalledocumentoestandarizado',
            name='tipo_nodo',
            field=models.CharField(choices=[('actividad', 'Actividad'), ('decision', 'Decision'), ('inicio', 'Inicio'), ('fin', 'Fin')], default='actividad', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalledocumentoestandarizado',
            name='recurso',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='ConexionDetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condicion', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('normal', 'Normal'), ('si', 'Si'), ('no', 'No'), ('alternativo', 'Alternativo'), ('retorno', 'Retorno')], default='normal', max_length=30)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_entrada', to='app.detalledocumentoestandarizado')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='app.encabezadodocumentoestandarizacion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_salida', to='app.detalledocumentoestandarizado')),
            ],
            options={
                'ordering': ['documento_id', 'id'],
                'unique_together': {('documento', 'origen', 'destino', 'tipo')},
            },
        ),
    ]
