# Generated by Django 6.0 on 2026-05-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_reporteiperc_tarea_medidacorrectiva_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporteiperc',
            options={'ordering': ['-fecha', 'orden_trabajo_id', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='reporteiperc',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reporteiperc',
            name='secuencia',
        ),
        migrations.RemoveField(
            model_name='reporteiperc',
            name='supervisor',
        ),
    ]
