# Generated by Django 6.0 on 2026-05-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_reporteiperc_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteiperc',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_iperc', to='app.ordentrabajo'),
        ),
    ]
