# Generated by Django 6.0 on 2026-05-25 11:32

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_reporteiperc_orden_trabajo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActividadChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('tipo_respuesta', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Numero'), ('BOOLEANO', 'Booleano'), ('OPCION', 'Opcion')], default='BOOLEANO', max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('requiere_observacion', models.BooleanField(default=False)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_checklist', to='app.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('fecha', models.DateField(default=app.models.current_local_date)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='BORRADOR', max_length=15)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('obligatorio', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists', to='app.actividadchecklist')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_checklist', to='app.checklist')),
                ('sistema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_actividades', to='app.sistema')),
            ],
            options={
                'ordering': ['checklist_id', 'orden', 'id'],
                'unique_together': {('checklist', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(default=app.models.current_local_date)),
                ('motivo', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=15)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='app.checklist')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_ejecuciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=150)),
                ('fecha', models.DateField(default=app.models.current_local_date)),
                ('estandarizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='app.tareaporestandarizar')),
            ],
            options={
                'ordering': ['-fecha', 'nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valor_texto', models.TextField(blank=True, default='')),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('valor_opcion', models.CharField(blank=True, default='', max_length=255)),
                ('observacion', models.TextField(blank=True, default='')),
                ('checklist_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app.checklistactividad')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app.checklistejecucion')),
            ],
            options={
                'ordering': ['ejecucion_id', 'checklist_actividad_id', 'id'],
                'unique_together': {('ejecucion', 'checklist_actividad')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asistencia', models.BooleanField(default=False)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_evento', to='app.trabajador')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app.evento')),
            ],
            options={
                'ordering': ['evento_id', 'trabajador_id'],
                'unique_together': {('trabajador', 'evento')},
            },
        ),
    ]
