# Generated by Django 6.0 on 2026-05-25 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_sistema_actividadchecklist_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistejecucion',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='horometro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_ejecuciones', to='app.ubicacioncliente'),
        ),
        migrations.AddField(
            model_name='checklistejecucion',
            name='maquinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_ejecuciones', to='app.maquinaria'),
        ),
        migrations.AddField(
            model_name='checklistrespuesta',
            name='vb',
            field=models.BooleanField(default=False),
        ),
    ]
